---
# Ansible role to install cobbler - main.yml
#
# Copyright (C) 2016  Mark Einon <mark.einon@gmail.com>
# Copyright (C) 2017  Erik McCormick <emccormickva@gmail.com>
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License,
# Version 2.1 only as published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#

- name: install epel
  yum: name=epel-release state=installed

- name: install cobbler packages
  yum: name={{ item }} state=installed
  with_items: "{{ cobbler_packages }}"

- name: configure cobbler settings
  template: src=settings.j2 dest=/etc/cobbler/settings backup=yes

- name: configure cobbler modules.conf
  template: src=modules.conf.j2 dest=/etc/cobbler/modules.conf backup=yes

- name: configure cobbler named.template
  template: src=named.template.j2 dest=/etc/cobbler/named.template backup=yes

- name: configure cobbler zone.template
  template: src=zone.template.j2 dest=/etc/cobbler/zone_templates/{{ item }} backup=yes
  with_items: zone_name

- name: configure cobbler dhcp.template
  template: src=dhcp.template.j2 dest=/etc/cobbler/dhcp.template backup=yes

- name: configure tftp settings
  template: src=tftp.j2 dest=/etc/xinetd.d/tftp backup=yes

- name: restart services (httpd, cobblerd, xinetd)
  service: name={{ item }} state=restarted enabled=yes
  with_items: "{{ cobbler_services }}"

- name: sync cobbler
  command: cobbler sync

...
